app:
  name: refrigerator
  home: C:\${app.name}

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:${app.home}\db\${app.name};MODE=PostgreSQL
    username: sa
    password: 
    
server:
  port: 8084